"""
Summarization Agent
--------------------
Turns reconciled, structured data into the final discharge summary + care plan.

Design choice: the safety-flags section is built directly from `conflicts` in
plain Python, NOT generated by the LLM. The LLM only writes the narrative
(patient course, meds, follow-up). This guarantees a flagged conflict can
never be silently dropped or softened by the model.
"""
from app.llm_client import call_llm

SUMMARY_SYSTEM_PROMPT = (
    "You are a clinical writing assistant. Write a clear, professional discharge "
    "summary narrative from the structured data given. Do not invent facts not "
    "present in the data. Do not mention medication safety conflicts -- those are "
    "handled in a separate section that will be added automatically."
)

SUMMARY_TEMPLATE = """Write a discharge summary narrative (3-5 short paragraphs) using ONLY this data:

Patient: {patient_info}
Diagnoses: {diagnoses}
Medications at discharge: {medications}
Key lab results: {lab_values}
Follow-up plan: {follow_up}

Cover: reason for admission and diagnoses, hospital course in plain terms, discharge
medications, and follow-up instructions. Do not add a safety/conflicts section --
that gets appended separately. Plain prose, no markdown headers.
"""


def _format_conflicts_section(conflicts: list) -> str:
    if not conflicts:
        return ""
    lines = ["\n\n⚠ MEDICATION SAFETY FLAGS (auto-detected, requires clinician review):"]
    for c in conflicts:
        lines.append(
            f"- {c['medication'].title()}: {c['concern']} "
            f"(triggered by {c['lab_test']} = {c['lab_value']}, threshold {c['threshold']})"
        )
    return "\n".join(lines)

def _compute_lab_trends(lab_values: list) -> list:
    """Find tests with both a baseline and current reading, compute direction
    deterministically -- don't trust prose narration to get a numeric comparison right."""
    by_test = {}
    for lab in lab_values or []:
        test = (lab.get("test") or "").lower().strip()
        timing = lab.get("timing")
        if timing in ("baseline", "current") and isinstance(lab.get("value"), (int, float)):
            by_test.setdefault(test, {})[timing] = lab["value"]

    trends = []
    for test, values in by_test.items():
        if "baseline" in values and "current" in values:
            baseline, current = values["baseline"], values["current"]
            direction = "worsened" if current > baseline else "improved" if current < baseline else "unchanged"
            trends.append(f"{test.title()}: {baseline} -> {current} ({direction})")
    return trends

def run_summarization(state: dict) -> dict:
    extracted = state.get("extracted_data") or {}
    conflicts = state.get("conflicts") or []

    prompt = SUMMARY_TEMPLATE.format(
        patient_info=extracted.get("patient_info", {}),
        diagnoses=extracted.get("diagnoses", []),
        medications=extracted.get("medications", []),
        lab_values=extracted.get("lab_values", []),
        follow_up=extracted.get("follow_up", []),
    )
    narrative = call_llm(prompt, system=SUMMARY_SYSTEM_PROMPT)
    trends = _compute_lab_trends(extracted.get("lab_values"))
    trends_section = "\n\nKey lab trends: " + "; ".join(trends) if trends else ""
    state["discharge_summary"] = narrative.strip() + trends_section + _format_conflicts_section(conflicts)
    return state


if __name__ == "__main__":
    # Fixed fixture (extracted_data + conflicts) so this agent is testable on its own,
    # without needing extraction/reconciliation to run first.
    test_state = {
        "extracted_data": {
            "patient_info": {"name": "Jane Doe", "mrn": "TEST-00123", "dob": "14-Mar-1958",
                              "admission_date": "10-Aug-2026", "discharge_date": "15-Aug-2026"},
            "diagnoses": ["Community-acquired pneumonia, right lower lobe", "Acute-on-chronic kidney injury, CKD Stage 3b"],
            "medications": [
                {"name": "Vancomycin", "dose": "1g", "frequency": "q8h", "route": "IV"},
                {"name": "Lisinopril", "dose": "10mg", "frequency": "once daily", "route": "PO"},
                {"name": "Metformin", "dose": "1000mg", "frequency": "twice daily", "route": "PO"},
            ],
            "lab_values": [
                {"test": "Potassium", "value": 5.2, "unit": "mmol/L", "flag": "HIGH"},
                {"test": "eGFR", "value": 27, "unit": "mL/min/1.73m2", "flag": "LOW"},
            ],
            "follow_up": ["Nephrology in 2 weeks", "PCP in 1 week"],
        },
        "conflicts": [
            {"medication": "vancomycin", "lab_test": "eGFR", "lab_value": 27, "threshold": 50,
             "concern": "Standard interval dosing without adjustment risks toxic accumulation when renal clearance is reduced.",
             "severity": "moderate"},
            {"medication": "metformin", "lab_test": "eGFR", "lab_value": 27, "threshold": 30,
             "concern": "Contraindicated below eGFR 30 due to risk of lactic acidosis.",
             "severity": "high"},
            {"medication": "lisinopril", "lab_test": "Potassium", "lab_value": 5.2, "threshold": 5.0,
             "concern": "ACE inhibitors can worsen hyperkalemia; potassium is already elevated.",
             "severity": "moderate"},
        ],
    }
    result = run_summarization(test_state)
    print(result["discharge_summary"])